from typing import Any

from manim import Scene

type HighlightResult = Any
type Region = Any
type Remove = Any

ArrayEntry: Any
ArrayMob: Any
ArrayPointer: Any
Caption: Any
Chrome: Any
DN: Any
DeckManifest: Any
DismissPaper: Any
Edge: Any
GhostSlideFade: Any
MainSlide: Any
Node: Any
OutlinePart: Any
OutlineProgressBar: Any
OutlineScene: Any
Paper: Any
PickPage: Any
SIMPLEX_DARK: Any
ShowPaper: Any
SimplexSectionType: Any
Subsection: Any
TexPage: Any
TransformByGlyphMap: Any
VT: Any
active_theme: Any
presets: Any

class BaseSlide(Scene):
    region: Any

    def next_slide(self, *args: Any, **kwargs: Any) -> None: ...

def apply_theme_defaults(*args: Any, **kwargs: Any) -> Any: ...
def bounding_box(*args: Any, **kwargs: Any) -> Any: ...
def clear_scene(*args: Any, **kwargs: Any) -> Any: ...
def code_block(*args: Any, **kwargs: Any) -> Any: ...
def code_explain(*args: Any, **kwargs: Any) -> Any: ...
def code_with_math(*args: Any, **kwargs: Any) -> Any: ...
def color_tex(*args: Any, **kwargs: Any) -> Any: ...
def debug_glyph(*args: Any, **kwargs: Any) -> Any: ...
def debug_glyphs(*args: Any, **kwargs: Any) -> Any: ...
def exit_for(*args: Any, **kwargs: Any) -> Any: ...
def get_active_theme(*args: Any, **kwargs: Any) -> Any: ...
def get_convex_hull_polygon(*args: Any, **kwargs: Any) -> Any: ...
def get_frame_center(*args: Any, **kwargs: Any) -> Any: ...
def get_surrounding_rectangle(*args: Any, **kwargs: Any) -> Any: ...
def highlight_code_lines(*args: Any, **kwargs: Any) -> Any: ...
def indexx_labels(*args: Any, **kwargs: Any) -> Any: ...
def keep_orientation(*args: Any, **kwargs: Any) -> Any: ...
def maintain_apparent_stroke_width(*args: Any, **kwargs: Any) -> Any: ...
def make_chrome(*args: Any, **kwargs: Any) -> Any: ...
def register_exit(*args: Any, **kwargs: Any) -> Any: ...
def scale_to_fit(*args: Any, **kwargs: Any) -> Any: ...
def scale_to_fit_mobject(*args: Any, **kwargs: Any) -> Any: ...
def scale_with_stroke_width(*args: Any, **kwargs: Any) -> Any: ...
def search_shape_in_text(*args: Any, **kwargs: Any) -> Any: ...
def set_exit_animation(*args: Any, **kwargs: Any) -> Any: ...
